### ISSUE TITLE
[Epic] - Moonstream 2.2 launch

### ISSUE THREAD

**Issue by oolumorin** [moonstream-to/api#952]
https://simiotics.slack.com/docs/TK98MPQLA/F06546JEL9W

- [ ] #951 
- [ ] Add leaderboard metadata
- [ ] Add leaderboard versions
- [ ] Fix API endpoints /leaderboard → /leaderboards
- [ ] Change leaderboards to serve from api.moonstream.to
- [ ] Update leaderboard documentation
